[local]
localhost

[mongodb]
mongodb-dev.kesavatarun.in

[catalogue]
catalogue-dev.kesavatarun.in

[redis]
redis-dev.kesavatarun.in

[user]
user-dev.kesavatarun.in

[cart]
cart-dev.kesavatarun.in

[mysql]
mysql-dev.kesavatarun.in

[shipping]
shipping-dev.kesavatarun.in

[rabbitmq]
rabbitmq-dev.kesavatarun.in

[payment]
payment-dev.kesavatarun.in

[frontend]
frontend-dev.kesavatarun.in

[all:vars]
ansible_user="ec2-user" #Give the instance username
ansible_password="DevOps321" #Give the instance passwords