- name: App_setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app_setup.yaml

- name: NodeJS_setup
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs_setup.yaml

- name: Systemd_setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd_setup.yaml

- name: Start the user
  ansible.builtin.service:
    name: user
    state: restarted
    enabled: yes
