- name: Copy {{ component }} service file
  ansible.builtin.template:
    src: "{{ component }}.service.j2" #By using j2 we can easily know that we are calling template file
    dest: "/etc/systemd/system/{{ component }}.service"
  notify: Restart "{{ component }}"

- name: Daemon reload
  ansible.builtin.systemd_service:
    daemon_reload: true
